AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dna-integration-test

  Sample SAM Template for dna-integration-test

Globals:
  Function:
    Timeout: 20

Resources:
  MutantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dna-integration-test
      Handler: com.dna.analyzer.AnalyzerHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          mongodb_url:
      Events:
        Mutant:
          Type: Api
          Properties:
            Path: /mutant
            Method: post

  StatsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dna-integration-test
      Handler: com.dna.stats.StatsHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          mongodb_url:
      Events:
        Stats:
          Type: Api
          Properties:
            Path: /stats
            Method: get
